<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<Version>10.1.0</Version>
		<Title>RA Utilities Data Entities</Title>                                                                                                                                                                                                                             
    <Description>
			Provides strongly typed, generic base classes for domain and data entities in .NET and EF Core.
			Features a flexible hierarchy with generic primary keys (TKey), distinct creation-only (BaseEntity) and mutable (WriteEntity) timestamp tracking, user   
			auditing (AuditableBaseEntity), and soft deletion (SoftDeleteEntity) to promote consistency across data models.
		</Description>                                                                                                                                           
    <PackageTags>RA;Utilities;Data;Entities;CoreEntity;BaseEntity;WriteEntity;Auditable;SoftDelete;EFCore;EntityFramework;ORM;Domain;DDD;GenericKey</PackageTags>
		<PackageIcon>entity.png</PackageIcon>
		<PackageId>RA.Utilities.Data.Entities</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotesFile>releasenotes.md</PackageReleaseNotesFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../../Assets/Images/entity.png" Pack="true" PackagePath="\" />
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="releasenotes.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
