using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RA.Utilities.Api.Generators.Models;

namespace RA.Utilities.Api.Generators;

/// <summary>
/// Builds the generated implementation of the <c>MapEndpoints</c> registration extension method and
/// reports the group-name validation diagnostics.
/// </summary>
internal static class SourceEmitter
{
    /// <summary>
    /// The standard header for generated files. The <c>auto-generated</c> marker makes analyzers skip
    /// the file, and the pragma silences compiler warnings (such as CS1591) in consumer projects
    /// that build with warnings as errors.
    /// </summary>
    private const string GeneratedFileHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

    /// <summary>
    /// The hint name of the generated source file.
    /// </summary>
    private const string HintName = "RA.Utilities.Api.EndpointRegistrations.g.cs";

    /// <summary>
    /// Emits the generated registration method and reports validation diagnostics for the discovered
    /// group and endpoint models.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="groups">The discovered <c>IEndpointGroup</c> implementations.</param>
    /// <param name="endpoints">The discovered <c>IEndpoint</c> implementations.</param>
    public static void Emit(
        SourceProductionContext context,
        EquatableArray<EndpointModel> groups,
        EquatableArray<EndpointModel> endpoints)
    {
        // Partial declarations yield one model per part; deduplicate on the model's value equality.
        groups = Sort(groups.Distinct());
        endpoints = Sort(endpoints.Distinct());

        ReportTypeValidation(context, groups);
        ReportTypeValidation(context, endpoints);
        ReportGroupNameValidation(context, groups);
        ReportEndpointNameValidation(context, groups, endpoints);

        context.AddSource(HintName, SourceText.From(BuildSource(groups, endpoints), Encoding.UTF8));
    }

    /// <summary>
    /// Reports the per-type diagnostics (generic types, inaccessible types, explicit static
    /// implementations) attached to the discovered models.
    /// </summary>
    private static void ReportTypeValidation(SourceProductionContext context, EquatableArray<EndpointModel> models)
    {
        foreach (EndpointModel model in models)
        {
            if (model.Diagnostic is DiagnosticModel diagnostic)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    diagnostic.Descriptor,
                    diagnostic.Location,
                    diagnostic.Arguments));
            }
        }
    }

    private static EquatableArray<EndpointModel> Sort(IEnumerable<EndpointModel> models) =>
        models.OrderBy(model => model.FullyQualifiedName, StringComparer.Ordinal).ToImmutableArray();

    /// <summary>
    /// Reports <c>EPMG001</c> for every group whose constant <c>GroupName</c> is shared with another group.
    /// Groups with non-constant names cannot be compared at compile time; a duplicate among them
    /// fails at startup with the exception thrown by the generated <c>AddGroup</c> helper.
    /// </summary>
    private static void ReportGroupNameValidation(SourceProductionContext context, EquatableArray<EndpointModel> groups)
    {
        foreach (IGrouping<string, EndpointModel> duplicate in groups
            .Where(model => model.GroupNameConstant is not null)
            .GroupBy(model => model.GroupNameConstant!)
            .Where(grouping => grouping.Count() > 1))
        {
            foreach (EndpointModel model in duplicate)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DuplicateGroupName,
                    model.Location,
                    model.TypeName,
                    duplicate.Key));
            }
        }
    }

    /// <summary>
    /// Reports <c>EPMG002</c> for every endpoint whose constant <c>GroupName</c> does not match any
    /// discovered group. Endpoints with non-constant names are resolved at runtime; a mismatch then
    /// fails at startup with the exception thrown by the generated <c>GetGroup</c> helper.
    /// </summary>
    private static void ReportEndpointNameValidation(
        SourceProductionContext context,
        EquatableArray<EndpointModel> groups,
        EquatableArray<EndpointModel> endpoints)
    {
        var groupNames = new HashSet<string>(
            groups.Where(model => model.GroupNameConstant is not null).Select(model => model.GroupNameConstant!),
            StringComparer.Ordinal);

        foreach (EndpointModel endpoint in endpoints.Where(model => model.GroupNameConstant is not null))
        {
            if (!groupNames.Contains(endpoint.GroupNameConstant!))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.UnknownGroupName,
                    endpoint.Location,
                    endpoint.TypeName,
                    endpoint.GroupNameConstant));
            }
        }
    }

    private static string BuildSource(EquatableArray<EndpointModel> groups, EquatableArray<EndpointModel> endpoints)
    {
        // Types that only produced a diagnostic carry no usable reference and must not be emitted.
        groups = groups.Where(model => !model.IsDiagnostic).ToImmutableArray();
        endpoints = endpoints.Where(model => !model.IsDiagnostic).ToImmutableArray();

        var builder = new StringBuilder();
        builder.Append(GeneratedFileHeader);
        builder.Append("namespace ").Append(KnownMetadataNames.RegistrationNamespace).Append('\n');
        builder.Append("{\n");

        AppendLine(builder, 1, $"public static partial class {KnownMetadataNames.RegistrationClassName}");
        AppendLine(builder, 1, "{");
        // The method is deliberately not partial: a partial method with accessibility modifiers must
        // have its implementing declaration in the same compilation as the defining declaration, but
        // the defining declaration lives in the RA.Utilities.Api assembly while this implementation
        // is generated into the consuming assembly.
        AppendLine(builder, 2, $"public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder {KnownMetadataNames.MapEndpointsMethod}(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)");
        AppendLine(builder, 2, "{");

        if (!groups.IsDefaultOrEmpty)
        {
            AppendLine(builder, 3, "global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups = new global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder>();");
            builder.Append('\n');

            foreach (EndpointModel group in groups)
            {
                AppendLine(builder, 3, $"AddGroup(groups, {group.FullyQualifiedName}.{KnownMetadataNames.GroupNameMember}, {group.FullyQualifiedName}.{KnownMetadataNames.MapGroupMember}(builder));");
            }

            builder.Append('\n');
        }

        foreach (EndpointModel endpoint in endpoints)
        {
            if (groups.IsDefaultOrEmpty)
            {
                AppendLine(builder, 3, $"{endpoint.FullyQualifiedName}.{KnownMetadataNames.MapEndpointMember}(GetGroupOrThrow(\"{endpoint.TypeName}\", {endpoint.FullyQualifiedName}.{KnownMetadataNames.GroupNameMember}));");
            }
            else
            {
                AppendLine(builder, 3, $"{endpoint.FullyQualifiedName}.{KnownMetadataNames.MapEndpointMember}(GetGroup(groups, \"{endpoint.TypeName}\", {endpoint.FullyQualifiedName}.{KnownMetadataNames.GroupNameMember}));");
            }
        }

        AppendLine(builder, 3, "return builder;");
        AppendLine(builder, 2, "}");

        if (!groups.IsDefaultOrEmpty)
        {
            AppendAddGroupHelper(builder);
            AppendGetGroupHelper(builder);
        }
        else if (!endpoints.IsDefaultOrEmpty)
        {
            AppendGetGroupOrThrowHelper(builder);
        }

        AppendLine(builder, 1, "}");
        builder.Append("}\n");

        return builder.ToString();
    }

    private static void AppendAddGroupHelper(StringBuilder builder)
    {
        builder.Append('\n');
        AppendLine(builder, 2, "private static void AddGroup(global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups, string groupName, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder group)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (groups.ContainsKey(groupName))");
        AppendLine(builder, 3, "{");
        AppendLine(builder, 4, "throw new global::System.InvalidOperationException(\"Multiple IEndpointGroup implementations declare the GroupName '\" + groupName + \"'. Group names must be unique within the assembly.\");");
        AppendLine(builder, 3, "}");
        builder.Append('\n');
        AppendLine(builder, 3, "groups.Add(groupName, group);");
        AppendLine(builder, 2, "}");
    }

    private static void AppendGetGroupHelper(StringBuilder builder)
    {
        builder.Append('\n');
        AppendLine(builder, 2, "private static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder GetGroup(global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups, string endpointTypeName, string groupName)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (!groups.TryGetValue(groupName, out global::Microsoft.AspNetCore.Routing.RouteGroupBuilder? group))");
        AppendLine(builder, 3, "{");
        AppendLine(builder, 4, "throw new global::System.InvalidOperationException(\"Endpoint '\" + endpointTypeName + \"' references endpoint group '\" + groupName + \"', but no IEndpointGroup with that GroupName is registered.\");");
        AppendLine(builder, 3, "}");
        builder.Append('\n');
        AppendLine(builder, 3, "return group;");
        AppendLine(builder, 2, "}");
    }

    private static void AppendGetGroupOrThrowHelper(StringBuilder builder)
    {
        builder.Append('\n');
        AppendLine(builder, 2, "private static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder GetGroupOrThrow(string endpointTypeName, string groupName)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "throw new global::System.InvalidOperationException(\"Endpoint '\" + endpointTypeName + \"' references endpoint group '\" + groupName + \"', but no IEndpointGroup implementations were found in this assembly.\");");
        AppendLine(builder, 2, "}");
    }

    private static void AppendLine(StringBuilder builder, int depth, string text) =>
        builder.Append(' ', depth * 4).Append(text).Append('\n');
}
