using System;
using System.Linq;
using System.Reflection;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace RA.Utilities.Tests.Generators;

public class HandlerRegistrationGeneratorTests
{
    private const string HandlerSources = """
        namespace Sample
        {
            public record Ping(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>;

            public record Pong(string Value);

            public class PingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Ping, Pong>
            {
                public System.Threading.Tasks.Task<Pong> HandleAsync(Ping request, System.Threading.CancellationToken cancellationToken) =>
                    System.Threading.Tasks.Task.FromResult(new Pong(request.Value));
            }

            public record DoNothing : global::RA.Utilities.Feature.Abstractions.IRequest;

            public class DoNothingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<DoNothing>
            {
                public System.Threading.Tasks.Task HandleAsync(DoNothing request, System.Threading.CancellationToken cancellationToken) =>
                    System.Threading.Tasks.Task.CompletedTask;
            }

            public record OrderPlaced : global::RA.Utilities.Feature.Abstractions.INotification;

            public class EmailNotifier : global::RA.Utilities.Feature.Abstractions.INotificationHandler<OrderPlaced>
            {
                public System.Threading.Tasks.Task HandleAsync(OrderPlaced notification, System.Threading.CancellationToken cancellationToken) =>
                    System.Threading.Tasks.Task.CompletedTask;
            }
        }
        """;

    private const string AbstractBaseSources = """
        namespace Sample
        {
            public record SpecialPing(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>;

            public record Pong(string Value);

            public abstract class AbstractPingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<SpecialPing, Pong>
            {
                public abstract System.Threading.Tasks.Task<Pong> HandleAsync(SpecialPing request, System.Threading.CancellationToken cancellationToken);
            }

            public class SpecialPingHandler : AbstractPingHandler
            {
                public override System.Threading.Tasks.Task<Pong> HandleAsync(SpecialPing request, System.Threading.CancellationToken cancellationToken) =>
                    System.Threading.Tasks.Task.FromResult(new Pong(request.Value));
            }
        }
        """;

    private const string ExpectedGeneratedSource = """"
        // <auto-generated/>
        #pragma warning disable
        #nullable enable

        namespace RA.Utilities.Feature.Generated
        {
            internal static class HandlerRegistrationInitializer
            {
                [global::System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Initialize()
                {
                    global::RA.Utilities.Feature.Generated.HandlerRegistrations.Add(static services =>
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::RA.Utilities.Feature.Abstractions.INotificationHandler<global::Sample.OrderPlaced>, global::Sample.EmailNotifier>(services);
                        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::RA.Utilities.Feature.Abstractions.IRequestHandler<global::Sample.DoNothing>, global::Sample.DoNothingHandler>(services);
                        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::RA.Utilities.Feature.Abstractions.IRequestHandler<global::Sample.Ping, global::Sample.Pong>, global::Sample.PingHandler>(services);
                    });
                }
            }
        }
        """";

    [Fact]
    public void GeneratesModuleInitializer_ForAllHandlerKinds()
    {
        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources, HandlerSources);

        runResult.Diagnostics.Should().BeEmpty();
        GeneratedSourceResult generatedSource = runResult.Results.Single().GeneratedSources.Should().ContainSingle().Subject;
        generatedSource.HintName.Should().Be("RA.Utilities.Feature.HandlerRegistrations.g.cs");
        generatedSource.SourceText.ToString().Should().Be(ExpectedGeneratedSource.Replace("\r\n", "\n") + "\n");
    }

    [Fact]
    public void ConcreteHandler_DerivingFromAbstractBase_IsRegisteredAsItself()
    {
        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources, AbstractBaseSources);

        runResult.Diagnostics.Should().BeEmpty();
        string generated = runResult.Results.Single().GeneratedSources.Single().SourceText.ToString();

        generated.Should().Contain("IRequestHandler<global::Sample.SpecialPing, global::Sample.Pong>, global::Sample.SpecialPingHandler>");
        generated.Should().NotContain("AbstractPingHandler");
    }

    [Fact]
    public void GenericHandler_ReportsWarning_FEAG002()
    {
        const string sources = """
            namespace Sample
            {
                public record Pong(string Value);

                public class GenericHandler<TRequest> : global::RA.Utilities.Feature.Abstractions.IRequestHandler<TRequest, Pong>
                    where TRequest : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>
                {
                    public System.Threading.Tasks.Task<Pong> HandleAsync(TRequest request, System.Threading.CancellationToken cancellationToken) =>
                        System.Threading.Tasks.Task.FromResult(new Pong("value"));
                }
            }
            """;

        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources, sources);

        runResult.Diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "FEAG002");
        runResult.Results.Single().GeneratedSources.Should().BeEmpty();
    }

    [Fact]
    public void PrivateNestedHandler_ReportsError_FEAG003()
    {
        const string sources = """
            namespace Sample
            {
                public record Ping(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>;

                public record Pong(string Value);

                public class Outer
                {
                    private class PrivatePingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Ping, Pong>
                    {
                        public System.Threading.Tasks.Task<Pong> HandleAsync(Ping request, System.Threading.CancellationToken cancellationToken) =>
                            System.Threading.Tasks.Task.FromResult(new Pong(request.Value));
                    }
                }
            }
            """;

        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources, sources);

        runResult.Diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "FEAG003");
        runResult.Results.Single().GeneratedSources.Should().BeEmpty();
    }

    [Fact]
    public void StructHandler_ReportsError_FEAG004()
    {
        const string sources = """
            namespace Sample
            {
                public record Ping(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>;

                public record Pong(string Value);

                public struct StructPingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Ping, Pong>
                {
                    public System.Threading.Tasks.Task<Pong> HandleAsync(Ping request, System.Threading.CancellationToken cancellationToken) =>
                        System.Threading.Tasks.Task.FromResult(new Pong(request.Value));
                }
            }
            """;

        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources, sources);

        runResult.Diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "FEAG004");
        runResult.Results.Single().GeneratedSources.Should().BeEmpty();
    }

    [Fact]
    public void DuplicateRequestHandlers_ReportError_FEAG005()
    {
        const string sources = """
            namespace Sample
            {
                public record Ping(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>;

                public record Pong(string Value);

                public class FirstPingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Ping, Pong>
                {
                    public System.Threading.Tasks.Task<Pong> HandleAsync(Ping request, System.Threading.CancellationToken cancellationToken) =>
                        System.Threading.Tasks.Task.FromResult(new Pong(request.Value));
                }

                public class SecondPingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Ping, Pong>
                {
                    public System.Threading.Tasks.Task<Pong> HandleAsync(Ping request, System.Threading.CancellationToken cancellationToken) =>
                        System.Threading.Tasks.Task.FromResult(new Pong(request.Value));
                }
            }
            """;

        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources, sources);

        runResult.Diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == "FEAG005");
    }

    [Fact]
    public void NoRuntimeContractsReferenced_GeneratesNothing()
    {
        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(HandlerSources);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.Results.Single().GeneratedSources.Should().BeEmpty();
    }

    [Fact]
    public void NoHandlers_GeneratesNothing()
    {
        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunGenerator(GeneratorTestHost.RuntimeSources);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.Results.Single().GeneratedSources.Should().BeEmpty();
    }

    [Fact]
    public void CompileAndLoad_ModuleInitializer_QueuesRegistrations()
    {
        Assembly assembly = GeneratorTestHost.CompileAndLoad(GeneratorTestHost.RuntimeSources, HandlerSources);

        // Assembly.Load runs the generated module initializer, which queues registrations into the
        // in-memory copy of HandlerRegistrations; applying them to a real ServiceCollection must
        // register the discovered handlers.
        Type handlerRegistrationsType = assembly.GetType("RA.Utilities.Feature.Generated.HandlerRegistrations")
            ?? throw new InvalidOperationException("HandlerRegistrations type not found in the emitted assembly.");
        MethodInfo applyAll = handlerRegistrationsType.GetMethod("ApplyAll", BindingFlags.Public | BindingFlags.Static)
            ?? throw new InvalidOperationException("ApplyAll method not found.");

        var services = new ServiceCollection();
        applyAll.Invoke(null, [services]);

        Type pingType = assembly.GetType("Sample.Ping")
            ?? throw new InvalidOperationException("Sample.Ping type not found in the emitted assembly.");
        Type pongType = assembly.GetType("Sample.Pong")
            ?? throw new InvalidOperationException("Sample.Pong type not found in the emitted assembly.");
        Type handlerInterfaceDefinition = assembly.GetType("RA.Utilities.Feature.Abstractions.IRequestHandler`2")
            ?? throw new InvalidOperationException("IRequestHandler<,> not found in the emitted assembly.");
        Type responseHandlerInterface = handlerInterfaceDefinition.MakeGenericType(pingType, pongType);

        using ServiceProvider provider = services.BuildServiceProvider();
        object? handler = provider.GetService(responseHandlerInterface);

        handler.Should().NotBeNull();
        handler.GetType().FullName.Should().Be("Sample.PingHandler");
    }
}
