using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace RA.Utilities.Tests.Generators;

/// <summary>
/// Verifies the shape of the source generated by the mediator implementation generator:
/// monomorphic per-message overloads, explicit interface implementations, the if-chain versus
/// fast-dictionary dispatch switch, and the message/handler diagnostics (FEAG006-FEAG009).
/// </summary>
public class MediatorImplementationGeneratorTests
{
    private const string GeneratedHintName = "RA.Utilities.Feature.MediatorImpl.g.cs";

    private const string BasicMessages = """
        using System.Threading;
        using System.Threading.Tasks;

        namespace Sample
        {
            public record Ping(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<Pong>;

            public record Pong(string Value);

            public class PingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Ping, Pong>
            {
                public Task<Pong> HandleAsync(Ping request, CancellationToken cancellationToken) => Task.FromResult(new Pong(request.Value));
            }

            public record DoNothing : global::RA.Utilities.Feature.Abstractions.IRequest;

            public class DoNothingHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<DoNothing>
            {
                public Task HandleAsync(DoNothing request, CancellationToken cancellationToken) => Task.CompletedTask;
            }

            public record OrderPlaced(string OrderId) : global::RA.Utilities.Feature.Abstractions.INotification;

            public class OrderPlacedHandler : global::RA.Utilities.Feature.Abstractions.INotificationHandler<OrderPlaced>
            {
                public Task HandleAsync(OrderPlaced notification, CancellationToken cancellationToken) => Task.CompletedTask;
            }
        }
        """;

    [Fact]
    public void EmitsMonomorphicOverloads_ForEveryMessageKind()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("public global::System.Threading.Tasks.Task<global::Sample.Pong> Send(global::Sample.Ping request");
        generated.Should().Contain("public global::System.Threading.Tasks.Task<global::Sample.Pong> Send<TContext>(global::Sample.Ping request");
        generated.Should().Contain("public global::System.Threading.Tasks.Task Send(global::Sample.DoNothing request");
        generated.Should().Contain("public global::System.Threading.Tasks.Task Send<TContext>(global::Sample.DoNothing request");
        generated.Should().Contain("public async global::System.Threading.Tasks.Task Publish(global::Sample.OrderPlaced notification");
        generated.Should().Contain("public async global::System.Threading.Tasks.Task Publish<TContext>(global::Sample.OrderPlaced notification");
        generated.Should().Contain("public global::System.Threading.Tasks.Task<object?> Send(object request");
        generated.Should().Contain("public global::System.Threading.Tasks.Task Publish(object notification");
    }

    [Fact]
    public void MediatorImpl_IsStandalone_AndImplementsTheInterface()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("internal sealed class MediatorImpl : global::RA.Utilities.Feature.Abstractions.IMediator");
        generated.Should().Contain("public MediatorImpl(global::System.IServiceProvider provider, global::Microsoft.Extensions.Logging.ILogger<MediatorImpl> logger)");
        generated.Should().Contain("global::System.Threading.Tasks.Task global::RA.Utilities.Feature.Abstractions.IMediator.Send<TRequest>(TRequest request");
        generated.Should().Contain("global::System.Threading.Tasks.Task<TResponse> global::RA.Utilities.Feature.Abstractions.IMediator.Send<TRequest, TResponse>(TRequest request");
        generated.Should().Contain("global::System.Threading.Tasks.Task global::RA.Utilities.Feature.Abstractions.IMediator.Publish<TNotification>(TNotification notification");
        generated.Should().NotContain(": global::RA.Utilities.Feature.Mediator");
    }

    [Fact]
    public void EmitsRegistrationInitializer_WhenNotDisabled()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("internal static class MediatorRegistrationInitializer");
        generated.Should().Contain("global::RA.Utilities.Feature.Generated.MediatorRegistrations.Add(static services =>");
        generated.Should().Contain("AddScoped<MediatorImpl>(services)");
    }

    [Fact]
    public void SmallProject_UsesTypeChains_ForObjectDispatch_InsteadOfDictionaries()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("if (requestType == typeof(global::Sample.Ping))");
        generated.Should().Contain("if (requestType == typeof(global::Sample.DoNothing))");
        generated.Should().Contain("if (notificationType == typeof(global::Sample.OrderPlaced))");
        generated.Should().NotContain("s_sendObject");
        generated.Should().NotContain("s_publish");
    }

    [Fact]
    public void LargeProject_UsesFastDictionaries_ForObjectDispatch()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BuildManyMessagesSource(17)]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<MediatorImpl, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>>> s_sendObject");
        generated.Should().Contain("private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<MediatorImpl, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> s_publish");
        generated.Should().Contain("[typeof(global::Sample.Request0)] = static (impl, request, cancellationToken) =>");
        generated.Should().Contain("s_sendObject.TryGetValue(requestType");
        generated.Should().Contain("s_publish.TryGetValue(notificationType");
    }

    [Fact]
    public void ValueTypeResponse_UsesBoxingHelper_ForObjectDispatch()
    {
        const string sources = """
            using System.Threading;
            using System.Threading.Tasks;

            namespace Sample
            {
                public record CountRequest : global::RA.Utilities.Feature.Abstractions.IRequest<int>;

                public class CountHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<CountRequest, int>
                {
                    public Task<int> HandleAsync(CountRequest request, CancellationToken cancellationToken) => Task.FromResult(42);
                }
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("return BoxAsync(task);");
        generated.Should().Contain("private static async global::System.Threading.Tasks.Task<object?> BoxAsync<T>(global::System.Threading.Tasks.Task<T> task)");
    }

    [Fact]
    public void ReferenceTypeResponse_UsesUnsafeCast_ForObjectDispatch()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.Task<global::Sample.Pong>, global::System.Threading.Tasks.Task<object?>>(ref task);");
    }

    [Fact]
    public void StructMessage_EmitsOverload_WithoutNullCheck()
    {
        const string sources = """
            using System.Threading;
            using System.Threading.Tasks;

            namespace Sample
            {
                public struct StructRequest : global::RA.Utilities.Feature.Abstractions.IRequest<int>;

                public class StructHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<StructRequest, int>
                {
                    public Task<int> HandleAsync(StructRequest request, CancellationToken cancellationToken) => Task.FromResult(7);
                }
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("public global::System.Threading.Tasks.Task<int> Send(global::Sample.StructRequest request");

        // Struct messages need no null check: the mono overload goes straight to the concrete
        // handler resolution and the direct call (the unrelated Send(object) overload keeps its
        // own object null check).
        generated.Should().Contain("""
            public global::System.Threading.Tasks.Task<int> Send(global::Sample.StructRequest request, global::System.Threading.CancellationToken cancellationToken = default)
                    {
                        global::Sample.StructHandler handler =
            """);
        generated.Should().Contain("return handler.HandleAsync(request, cancellationToken);");
    }

    [Fact]
    public void DualResponseContracts_ReportFEAG006_AndExcludeTheMessage()
    {
        const string sources = """
            namespace Sample
            {
                public record Dual : global::RA.Utilities.Feature.Abstractions.IRequest<string>, global::RA.Utilities.Feature.Abstractions.IRequest<int>;
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        Diagnostic diagnostic = GetDiagnostics(runResult).Should().ContainSingle().Which;
        diagnostic.Id.Should().Be("FEAG006");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        diagnostic.GetMessage().Should().Contain("Dual");

        // A compilation whose only message is ambiguous emits no mediator at all.
        runResult.Results.SelectMany(static result => result.GeneratedSources).Should().BeEmpty();
    }

    [Fact]
    public void RequestAndNotificationContract_ReportsFEAG006()
    {
        const string sources = """
            namespace Sample
            {
                public record Mixed : global::RA.Utilities.Feature.Abstractions.IRequest<string>, global::RA.Utilities.Feature.Abstractions.INotification;
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        Diagnostic diagnostic = GetDiagnostics(runResult).Should().ContainSingle().Which;
        diagnostic.Id.Should().Be("FEAG006");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
    }

    [Fact]
    public void RedundantVoidAndResponseContract_IsTreatedAsResponseRequest_WithoutDiagnostic()
    {
        const string sources = """
            using System.Threading;
            using System.Threading.Tasks;

            namespace Sample
            {
                public record Redundant : global::RA.Utilities.Feature.Abstractions.IRequest, global::RA.Utilities.Feature.Abstractions.IRequest<string>;

                public class RedundantHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Redundant, string>
                {
                    public Task<string> HandleAsync(Redundant request, CancellationToken cancellationToken) => Task.FromResult("ok");
                }
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        GetDiagnostics(runResult).Should().BeEmpty();

        string generated = GetGeneratedSource(runResult);
        generated.Should().Contain("public global::System.Threading.Tasks.Task<string> Send(global::Sample.Redundant request");
        generated.Should().NotContain("public global::System.Threading.Tasks.Task Send(global::Sample.Redundant request");
    }

    [Fact]
    public void RequestWithoutHandler_ReportsFEAG007()
    {
        const string sources = """
            namespace Sample
            {
                public record OrphanRequest : global::RA.Utilities.Feature.Abstractions.IRequest<string>;
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        Diagnostic diagnostic = GetDiagnostics(runResult).Should().ContainSingle().Which;
        diagnostic.Id.Should().Be("FEAG007");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
        diagnostic.GetMessage().Should().Contain("OrphanRequest");
    }

    [Fact]
    public void RequestWithHandler_ReportsNoFEAG007()
    {
        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        GetDiagnostics(runResult).Should().BeEmpty();
    }

    [Fact]
    public void GenericMessage_ReportsFEAG008()
    {
        const string sources = """
            namespace Sample
            {
                public record GenericRequest<T> : global::RA.Utilities.Feature.Abstractions.IRequest<string>;
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        Diagnostic diagnostic = GetDiagnostics(runResult).Should().ContainSingle().Which;
        diagnostic.Id.Should().Be("FEAG008");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
    }

    [Fact]
    public void FileLocalMessage_ReportsFEAG008()
    {
        const string sources = """
            namespace Sample
            {
                file record FileLocalRequest : global::RA.Utilities.Feature.Abstractions.IRequest<string>;
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        Diagnostic diagnostic = GetDiagnostics(runResult).Should().ContainSingle().Which;
        diagnostic.Id.Should().Be("FEAG008");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
    }

    [Fact]
    public void HandlerWithBothContracts_ReportsFEAG009()
    {
        const string sources = """
            using System.Threading;
            using System.Threading.Tasks;

            namespace Sample
            {
                public record DualContractRequest : global::RA.Utilities.Feature.Abstractions.IRequest, global::RA.Utilities.Feature.Abstractions.IRequest<int>;

                public class DualContractHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<DualContractRequest>, global::RA.Utilities.Feature.Abstractions.IRequestHandler<DualContractRequest, int>
                {
                    public Task HandleAsync(DualContractRequest request, CancellationToken cancellationToken) => Task.CompletedTask;

                    public Task<int> HandleAsync(DualContractRequest request, CancellationToken cancellationToken) => Task.FromResult(1);
                }
            }
            """;

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([sources]);

        Diagnostic diagnostic = GetDiagnostics(runResult).Should().ContainSingle().Which;
        diagnostic.Id.Should().Be("FEAG009");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
        diagnostic.GetMessage().Should().Contain("DualContractHandler");
    }

    [Fact]
    public void SeamDefine_EmitsMediatorImpl_WithoutRegistrationInitializer()
    {
        CSharpParseOptions parseOptions = new CSharpParseOptions(LanguageVersion.Latest)
            .WithPreprocessorSymbols(GeneratorTestHost.DisableModuleInitializerDefine);

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator([BasicMessages], parseOptions);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("internal sealed class MediatorImpl");
        generated.Should().NotContain("MediatorRegistrationInitializer");
    }

    [Fact]
    public void NoRuntimeContracts_EmitsNothing()
    {
        (Compilation _, GeneratorDriverRunResult runResult) =
            GeneratorTestHost.RunMediatorGenerator([""], includeRealRuntime: false);

        runResult.Results.SelectMany(static result => result.GeneratedSources).Should().BeEmpty();
    }

    [Fact]
    public void ReferencedAssemblyMessages_AreIncluded_WhenAccessible()
    {
        const string librarySources = """
            using System.Threading;
            using System.Threading.Tasks;

            namespace Lib
            {
                public record LibRequest(string Value) : global::RA.Utilities.Feature.Abstractions.IRequest<string>;

                public class LibHandler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<LibRequest, string>
                {
                    public Task<string> HandleAsync(LibRequest request, CancellationToken cancellationToken) => Task.FromResult("ok");
                }

                internal record HiddenRequest : global::RA.Utilities.Feature.Abstractions.IRequest<string>;
            }
            """;

        MetadataReference library = GeneratorTestHost.CompileToReference([librarySources]);

        (_, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunMediatorGenerator(
            ["namespace App { public class Entry { } }"],
            additionalReferences: [library]);

        string generated = GetGeneratedSource(runResult);

        generated.Should().Contain("public global::System.Threading.Tasks.Task<string> Send(global::Lib.LibRequest request");
        generated.Should().NotContain("HiddenRequest");
        GetDiagnostics(runResult).Should().BeEmpty();
    }

    [Fact]
    public void Emission_IsDeterministic_AcrossRuns()
    {
        (_, GeneratorDriverRunResult firstRun) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);
        (_, GeneratorDriverRunResult secondRun) = GeneratorTestHost.RunMediatorGenerator([BasicMessages]);

        GetGeneratedSource(firstRun).Should().Be(GetGeneratedSource(secondRun));
    }

    private static string GetGeneratedSource(GeneratorDriverRunResult runResult) =>
        runResult.Results
            .SelectMany(static result => result.GeneratedSources)
            .Single(static source => source.HintName == GeneratedHintName)
            .SourceText.ToString();

    private static ImmutableArray<Diagnostic> GetDiagnostics(GeneratorDriverRunResult runResult) =>
        runResult.Results.SelectMany(static result => result.Diagnostics).ToImmutableArray();

    private static string BuildManyMessagesSource(int count)
    {
        var builder = new StringBuilder();
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("namespace Sample");
        builder.AppendLine("{");

        for (int i = 0; i < count; i++)
        {
            builder.AppendLine($"    public record Request{i} : global::RA.Utilities.Feature.Abstractions.IRequest<string>;");
            builder.AppendLine($"    public class Request{i}Handler : global::RA.Utilities.Feature.Abstractions.IRequestHandler<Request{i}, string>");
            builder.AppendLine("    {");
            builder.AppendLine($"        public Task<string> HandleAsync(Request{i} request, CancellationToken cancellationToken) => Task.FromResult(\"ok\");");
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }
}
