using RA.Utilities.Integrations.Attributes;

namespace RA.Utilities.Integrations.Tests.Models;

/// <summary>
/// A strongly-typed query parameter container used by the <see cref="BaseHttpClientTests"/>.
/// The partial implementation of <see cref="RA.Utilities.Integrations.Abstractions.IQueryStringRequest"/>
/// is generated by the source generator at build time.
/// </summary>
[QueryParameters]
public partial class ProductQuery
{
    /// <summary>
    /// Gets or sets the category filter.
    /// </summary>
    public int? CategoryId { get; set; }

    /// <summary>
    /// Gets or sets the search term.
    /// </summary>
    public string? Search { get; set; }
}

/// <summary>
/// A strongly-typed header parameter container used by the <see cref="BaseHttpClientTests"/>.
/// The partial implementation of <see cref="RA.Utilities.Integrations.Abstractions.IHeaderRequest"/>
/// is generated by the source generator at build time.
/// </summary>
[HeaderParameters]
public partial class ProductHeaders
{
    /// <summary>
    /// Gets or sets the trace identifier header.
    /// </summary>
    public string? XTraceId { get; set; }
}

/// <summary>
/// A sample response model.
/// </summary>
public class Product
{
    /// <summary>
    /// Gets or sets the product identifier.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the product name.
    /// </summary>
    public string Name { get; set; } = string.Empty;
}
