using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RA.Utilities.Feature.Generators.Models;

namespace RA.Utilities.Feature.Generators;

/// <summary>
/// Builds the generated <c>Mediator</c> class — the sole <c>IMediator</c> implementation —
/// with monomorphized per-message dispatch: the known handler is injected by concrete type and
/// called directly, behaviors resolve through DI (picking up both auto-registered and explicitly
/// registered pipeline behaviors), and the zero-behavior path calls the handler with no delegate
/// chain at all. The generic interface methods carry the same bodies, monomorphized by the JIT.
/// </summary>
internal static class MediatorEmitter
{
    /// <summary>
    /// The standard header for generated files. The <c>auto-generated</c> marker makes analyzers skip
    /// the file, and the pragma silences compiler warnings (such as CS1591) in consumer projects
    /// that build with warnings as errors.
    /// </summary>
    private const string GeneratedFileHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

    /// <summary>
    /// The hint name of the generated source file.
    /// </summary>
    private const string HintName = "RA.Utilities.Feature.Mediator.g.cs";

    /// <summary>
    /// The project-size threshold above which the object-based dispatch switches from
    /// <c>typeof</c> if-chains to static dictionary lookups.
    /// </summary>
    public const int DictionaryThreshold = 8;

    /// <summary>
    /// Emits the generated mediator implementation, its registration initializer, and the
    /// message/handler diagnostics.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="sourceMessages">The message models discovered in the current compilation.</param>
    /// <param name="sourceHandlers">The handler and behavior models discovered in the current compilation.</param>
    /// <param name="referenced">The models discovered in referenced assemblies.</param>
    /// <param name="contractsPresent">Whether the compilation references the runtime contracts.</param>
    /// <param name="moduleInitializersSupported">Whether the target framework supports module initializers.</param>
    /// <param name="initializerDisabled">Whether the registration initializer emission is disabled by the test seam.</param>
    public static void Emit(
        SourceProductionContext context,
        EquatableArray<MessageModel> sourceMessages,
        EquatableArray<HandlerModel> sourceHandlers,
        ReferencedAssemblyModels referenced,
        bool contractsPresent,
        bool moduleInitializersSupported,
        bool initializerDisabled)
    {
        if (!contractsPresent)
        {
            return;
        }

        EquatableArray<MessageModel> allMessages = CombineMessages(sourceMessages, referenced.Messages);
        EquatableArray<HandlerModel> allHandlers = CombineHandlers(sourceHandlers, referenced.Handlers);

        ReportDiagnostics(context, sourceMessages, allMessages, allHandlers);

        EquatableArray<MessageModel> cleanMessages = allMessages.Where(static message => !message.IsDiagnostic).ToImmutableArray();
        if (cleanMessages.IsDefaultOrEmpty)
        {
            return;
        }

        if (!moduleInitializersSupported)
        {
            context.ReportDiagnostic(Diagnostic.Create(Diagnostics.ModuleInitializersUnavailable, Location.None));
            return;
        }

        context.AddSource(HintName, SourceText.From(BuildSource(cleanMessages, allHandlers, initializerDisabled), Encoding.UTF8));
    }

    /// <summary>
    /// Combines the source and referenced message models, deduplicates on value equality (so
    /// partial declarations collapse), and sorts by kind and name for deterministic emission.
    /// </summary>
    private static EquatableArray<MessageModel> CombineMessages(
        EquatableArray<MessageModel> sourceMessages,
        EquatableArray<MessageModel> referencedMessages) =>
        sourceMessages
            .Concat(referencedMessages)
            .Distinct()
            .OrderBy(static message => message.Kind)
            .ThenBy(static message => message.MessageFullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

    private static EquatableArray<HandlerModel> CombineHandlers(
        EquatableArray<HandlerModel> sourceHandlers,
        EquatableArray<HandlerModel> referencedHandlers) =>
        sourceHandlers
            .Concat(referencedHandlers)
            .Distinct()
            .OrderBy(static handler => handler.Kind)
            .ThenBy(static handler => handler.HandlerFullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

    /// <summary>
    /// Reports the message contract diagnostics (FEAG006, FEAG008), the missing-handler warnings
    /// (FEAG007), and the dual-contract handler warnings (FEAG009).
    /// </summary>
    private static void ReportDiagnostics(
        SourceProductionContext context,
        EquatableArray<MessageModel> sourceMessages,
        EquatableArray<MessageModel> allMessages,
        EquatableArray<HandlerModel> allHandlers)
    {
        var reported = new HashSet<string>(StringComparer.Ordinal);

        foreach (MessageModel message in sourceMessages)
        {
            if (message.Diagnostic is not DiagnosticModel diagnostic)
            {
                continue;
            }

            string key = diagnostic.Descriptor.Id + "|" + message.TypeName;
            if (!reported.Add(key))
            {
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                diagnostic.Descriptor,
                diagnostic.Location,
                diagnostic.Arguments));
        }

        // FEAG007: in-source request messages without a handler anywhere in the compilation.
        var handledRequests = new HashSet<string>(StringComparer.Ordinal);
        foreach (HandlerModel handler in allHandlers)
        {
            if (!handler.IsDiagnostic && handler.Kind is HandlerKind.VoidRequest or HandlerKind.RequestResponse)
            {
                handledRequests.Add(handler.RequestFullyQualifiedName);
            }
        }

        foreach (MessageModel message in allMessages)
        {
            if (message.IsDiagnostic
                || message.Kind == MessageKind.Notification
                || message.Location == Location.None
                || handledRequests.Contains(message.MessageFullyQualifiedName))
            {
                continue;
            }

            string key = Diagnostics.RequestMessageHasNoHandler.Id + "|" + message.TypeName;
            if (!reported.Add(key))
            {
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.RequestMessageHasNoHandler,
                message.Location,
                message.TypeName));
        }

        // FEAG009: a handler class implementing both the void and the request/response contract
        // for the same message.
        var reportedHandlers = new HashSet<string>(StringComparer.Ordinal);
        foreach (IGrouping<(string Handler, string Request), HandlerModel> group in allHandlers
            .Where(static handler => !handler.IsDiagnostic
                && handler.Kind is HandlerKind.VoidRequest or HandlerKind.RequestResponse)
            .GroupBy(static handler => (handler.HandlerFullyQualifiedName, handler.RequestFullyQualifiedName)))
        {
            bool hasVoid = group.Any(static handler => handler.Kind == HandlerKind.VoidRequest);
            bool hasResponse = group.Any(static handler => handler.Kind == HandlerKind.RequestResponse);
            if (!hasVoid || !hasResponse)
            {
                continue;
            }

            string key = Diagnostics.HandlerImplementsBothContracts.Id + "|" + group.Key.Handler + "|" + group.Key.Request;
            if (!reportedHandlers.Add(key))
            {
                continue;
            }

            HandlerModel anchor = group.FirstOrDefault(static handler => handler.Location != Location.None);
            if (anchor.Location is null)
            {
                anchor = group.First();
            }

            context.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.HandlerImplementsBothContracts,
                anchor.Location,
                anchor.TypeName,
                StripGlobalPrefix(anchor.RequestFullyQualifiedName)));
        }
    }

    private static string StripGlobalPrefix(string fullyQualifiedName) =>
        fullyQualifiedName.StartsWith("global::", StringComparison.Ordinal)
            ? fullyQualifiedName.Substring("global::".Length)
            : fullyQualifiedName;

    /// <summary>
    /// Finds the concrete handler type for a message, or an empty string when the handler is
    /// generic or not discoverable (in which case the generated code resolves the handler
    /// interface instead).
    /// </summary>
    private static string GetHandlerFullyQualifiedName(EquatableArray<HandlerModel> allHandlers, MessageModel message)
    {
        foreach (HandlerModel handler in allHandlers)
        {
            if (!handler.IsDiagnostic
                && handler.Kind is HandlerKind.VoidRequest or HandlerKind.RequestResponse
                && string.Equals(handler.RequestFullyQualifiedName, message.MessageFullyQualifiedName, StringComparison.Ordinal))
            {
                return handler.HandlerFullyQualifiedName;
            }
        }

        return string.Empty;
    }

    private static string BuildSource(EquatableArray<MessageModel> messages, EquatableArray<HandlerModel> allHandlers, bool initializerDisabled)
    {
        EquatableArray<MessageModel> responseMessages = messages
            .Where(static message => message.Kind == MessageKind.RequestResponse)
            .ToImmutableArray();
        EquatableArray<MessageModel> voidMessages = messages
            .Where(static message => message.Kind == MessageKind.VoidRequest)
            .ToImmutableArray();
        EquatableArray<MessageModel> notifications = messages
            .Where(static message => message.Kind == MessageKind.Notification)
            .ToImmutableArray();

        bool useDictionaries = messages.Count > DictionaryThreshold;
        bool needsBoxAsync = responseMessages.Any(static message => message.ResponseIsValueType);
        bool needsToObjectTaskAsync = !useDictionaries && voidMessages.Count > 0;

        var builder = new StringBuilder();
        builder.Append(GeneratedFileHeader);
        builder.Append("namespace ").Append(KnownMetadataNames.GeneratedNamespace).Append('\n');
        builder.Append("{\n");

        AppendLine(builder, 1, "internal sealed class Mediator : global::RA.Utilities.Feature.Abstractions.IMediator");
        AppendLine(builder, 1, "{");
        AppendLine(builder, 2, "private readonly global::System.IServiceProvider _provider;");
        AppendLine(builder, 2, "private readonly global::Microsoft.Extensions.Logging.ILogger<Mediator> _logger;");
        AppendConstructor(builder);

        foreach (MessageModel message in responseMessages)
        {
            string handler = GetHandlerFullyQualifiedName(allHandlers, message);
            AppendResponseSend(builder, message, handler);
            AppendResponseContextSend(builder, message, handler);
        }

        foreach (MessageModel message in voidMessages)
        {
            string handler = GetHandlerFullyQualifiedName(allHandlers, message);
            AppendVoidSend(builder, message, handler);
            AppendVoidContextSend(builder, message, handler);
        }

        foreach (MessageModel message in notifications)
        {
            AppendPublish(builder, message);
            AppendContextPublish(builder, message);
        }

        AppendObjectSend(builder, responseMessages, voidMessages, useDictionaries);
        AppendObjectPublish(builder, notifications, useDictionaries);

        AppendVoidInterfaceSend(builder);
        AppendResponseInterfaceSend(builder);
        AppendVoidContextInterfaceSend(builder);
        AppendResponseContextInterfaceSend(builder);
        AppendPublishInterface(builder);
        AppendContextPublishInterface(builder);

        if (useDictionaries)
        {
            AppendObjectSendDictionary(builder, responseMessages, voidMessages);
            AppendPublishDictionary(builder, notifications);
        }

        AppendHelpers(builder, needsBoxAsync, needsToObjectTaskAsync);

        AppendLine(builder, 1, "}");
        builder.Append('\n');

        if (!initializerDisabled)
        {
            AppendInitializer(builder);
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    private static void AppendConstructor(StringBuilder builder)
    {
        AppendLine(builder, 2, "public Mediator(global::System.IServiceProvider provider, global::Microsoft.Extensions.Logging.ILogger<Mediator> logger)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (provider is null) { throw new global::System.ArgumentNullException(nameof(provider)); }");
        AppendLine(builder, 3, "if (logger is null) { throw new global::System.ArgumentNullException(nameof(logger)); }");
        AppendLine(builder, 3, "_provider = provider;");
        AppendLine(builder, 3, "_logger = logger;");
        AppendLine(builder, 2, "}");
    }

    // ------------------- shared body fragments -------------------

    private static void AppendRequestSendBody(
        StringBuilder builder,
        string messageType,
        string responseType,
        string nullCheckLine,
        string handlerServiceType,
        bool useInterfaceBehaviorCast)
    {
        if (nullCheckLine.Length > 0)
        {
            AppendLine(builder, 3, nullCheckLine);
        }

        AppendLine(builder, 3, $"{handlerServiceType} handler =");
        AppendLine(builder, 4, $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerServiceType}>(_provider);");

        AppendBehaviorEnumeration(builder, 3, messageType, responseType, hasResponse: true, useInterfaceBehaviorCast);
        AppendLine(builder, 3, "if (behaviors.Length == 0) { return handler.HandleAsync(request, cancellationToken); }");
        AppendLine(builder, 3, $"global::RA.Utilities.Feature.Models.RequestHandlerDelegate<{responseType}> next = () => handler.HandleAsync(request, cancellationToken);");
        AppendBehaviorChain(builder, 3, messageType, responseType, hasResponse: true, hasContext: false, useInterfaceBehaviorCast);
        AppendLine(builder, 3, "return next();");
    }

    private static void AppendRequestContextSendBody(
        StringBuilder builder,
        string messageType,
        string responseType,
        string nullCheckLine,
        string handlerServiceType,
        string handlerContextCall,
        bool useInterfaceBehaviorCast)
    {
        if (nullCheckLine.Length > 0)
        {
            AppendLine(builder, 3, nullCheckLine);
        }

        AppendLine(builder, 3, "global::RA.Utilities.Feature.Models.PipelineContext<TContext> ctx = context ?? new global::RA.Utilities.Feature.Models.PipelineContext<TContext>();");
        AppendLine(builder, 3, $"{handlerServiceType} handler =");
        AppendLine(builder, 4, $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerServiceType}>(_provider);");

        AppendBehaviorEnumeration(builder, 3, messageType, responseType, hasResponse: true, useInterfaceBehaviorCast);
        AppendLine(builder, 3, $"if (behaviors.Length == 0) {{ return {handlerContextCall.Replace("request, c, cancellationToken", "request, ctx, cancellationToken")}; }}");
        AppendLine(builder, 3, $"global::RA.Utilities.Feature.Models.RequestHandlerContextDelegate<{responseType}, TContext> next = c => {handlerContextCall};");
        AppendBehaviorChain(builder, 3, messageType, responseType, hasResponse: true, hasContext: true, useInterfaceBehaviorCast);
        AppendLine(builder, 3, "return next(ctx);");
    }

    private static void AppendVoidSendBody(
        StringBuilder builder,
        string messageType,
        string nullCheckLine,
        string handlerServiceType,
        bool useInterfaceBehaviorCast)
    {
        if (nullCheckLine.Length > 0)
        {
            AppendLine(builder, 3, nullCheckLine);
        }

        AppendLine(builder, 3, $"{handlerServiceType} handler =");
        AppendLine(builder, 4, $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerServiceType}>(_provider);");

        AppendBehaviorEnumeration(builder, 3, messageType, null, hasResponse: false, useInterfaceBehaviorCast);
        AppendLine(builder, 3, "if (behaviors.Length == 0) { return handler.HandleAsync(request, cancellationToken); }");
        AppendLine(builder, 3, "global::RA.Utilities.Feature.Models.RequestHandlerDelegate next = () => handler.HandleAsync(request, cancellationToken);");
        AppendBehaviorChain(builder, 3, messageType, null, hasResponse: false, hasContext: false, useInterfaceBehaviorCast);
        AppendLine(builder, 3, "return next();");
    }

    private static void AppendVoidContextSendBody(
        StringBuilder builder,
        string messageType,
        string nullCheckLine,
        string handlerServiceType,
        string handlerContextCall,
        bool useInterfaceBehaviorCast)
    {
        if (nullCheckLine.Length > 0)
        {
            AppendLine(builder, 3, nullCheckLine);
        }

        AppendLine(builder, 3, "global::RA.Utilities.Feature.Models.PipelineContext<TContext> ctx = context ?? new global::RA.Utilities.Feature.Models.PipelineContext<TContext>();");
        AppendLine(builder, 3, $"{handlerServiceType} handler =");
        AppendLine(builder, 4, $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerServiceType}>(_provider);");

        AppendBehaviorEnumeration(builder, 3, messageType, null, hasResponse: false, useInterfaceBehaviorCast);
        AppendLine(builder, 3, $"if (behaviors.Length == 0) {{ return {handlerContextCall.Replace("request, c, cancellationToken", "request, ctx, cancellationToken")}; }}");
        AppendLine(builder, 3, $"global::RA.Utilities.Feature.Models.RequestHandlerContextDelegate<TContext> next = c => {handlerContextCall};");
        AppendBehaviorChain(builder, 3, messageType, null, hasResponse: false, hasContext: true, useInterfaceBehaviorCast);
        AppendLine(builder, 3, "return next(ctx);");
    }

    /// <summary>
    /// Emits the behavior service enumeration. Closed monomorphic bodies use the direct array
    /// cast; the generic interface bodies use the variance-free <see cref="Array"/> cast so that
    /// JIT generic sharing cannot break the cast.
    /// </summary>
    private static void AppendBehaviorEnumeration(
        StringBuilder builder,
        int depth,
        string messageType,
        string? responseType,
        bool hasResponse,
        bool useInterfaceBehaviorCast)
    {
        string behaviorInterface = hasResponse
            ? $"global::RA.Utilities.Feature.Abstractions.IPipelineBehavior<{messageType}, {responseType}>"
            : $"global::RA.Utilities.Feature.Abstractions.IPipelineBehavior<{messageType}>";

        AppendLine(builder, depth, $"global::System.Collections.Generic.IEnumerable<{behaviorInterface}> behaviorServices =");
        AppendLine(builder, depth + 1, $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<{behaviorInterface}>(_provider);");

        if (useInterfaceBehaviorCast)
        {
            AppendLine(builder, depth, "global::System.Array behaviors = behaviorServices as global::System.Array ?? global::System.Linq.Enumerable.ToArray(behaviorServices);");
        }
        else
        {
            AppendLine(builder, depth, $"{behaviorInterface}[] behaviors = behaviorServices as {behaviorInterface}[] ?? global::System.Linq.Enumerable.ToArray(behaviorServices);");
        }
    }

    /// <summary>
    /// Emits the reversed delegate chain so the first registered behavior is outermost. Each step
    /// snapshots the current chain into a fresh local that is never reassigned — capturing the
    /// reassigned <c>next</c> variable itself would make every wrapper call itself recursively.
    /// </summary>
    private static void AppendBehaviorChain(
        StringBuilder builder,
        int depth,
        string messageType,
        string? responseType,
        bool hasResponse,
        bool hasContext,
        bool useInterfaceBehaviorCast)
    {
        string behaviorInterface = hasResponse
            ? $"global::RA.Utilities.Feature.Abstractions.IPipelineBehavior<{messageType}, {responseType}>"
            : $"global::RA.Utilities.Feature.Abstractions.IPipelineBehavior<{messageType}>";
        string delegateType;
        if (hasResponse)
        {
            delegateType = hasContext
                ? $"global::RA.Utilities.Feature.Models.RequestHandlerContextDelegate<{responseType}, TContext>"
                : $"global::RA.Utilities.Feature.Models.RequestHandlerDelegate<{responseType}>";
        }
        else
        {
            delegateType = hasContext
                ? "global::RA.Utilities.Feature.Models.RequestHandlerContextDelegate<TContext>"
                : "global::RA.Utilities.Feature.Models.RequestHandlerDelegate";
        }
        string elementRead = useInterfaceBehaviorCast
            ? $"({behaviorInterface})behaviors.GetValue(i)!"
            : "behaviors[i]";

        AppendLine(builder, depth, "for (int i = behaviors.Length - 1; i >= 0; i--)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, $"{behaviorInterface} behavior = {elementRead};");
        AppendLine(builder, depth + 1, $"{delegateType} previous = next;");
        AppendLine(builder, depth + 1, hasContext
            ? "next = c => behavior.HandleAsync<TContext>(request, previous, c, cancellationToken);"
            : "next = () => behavior.HandleAsync(request, previous, cancellationToken);");
        AppendLine(builder, depth, "}");
    }

    /// <summary>
    /// Emits the notification fan-out body mirroring the historical publish semantics
    /// (per-handler behavior wrapping and logged-and-swallowed handler failures).
    /// </summary>
    private static void AppendPublishBody(StringBuilder builder, string notificationType, bool hasContext)
    {
        AppendLine(builder, 3, $"global::System.Collections.Generic.List<global::RA.Utilities.Feature.Abstractions.INotificationHandler<{notificationType}>> handlers =");
        AppendLine(builder, 4, $"global::System.Linq.Enumerable.ToList(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::RA.Utilities.Feature.Abstractions.INotificationHandler<{notificationType}>>(_provider));");
        AppendLine(builder, 3, "if (handlers.Count == 0) { return; }");
        AppendLine(builder, 3, $"global::System.Collections.Generic.List<global::RA.Utilities.Feature.Abstractions.INotificationBehavior<{notificationType}>> behaviors =");
        AppendLine(builder, 4, $"global::System.Linq.Enumerable.ToList(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::RA.Utilities.Feature.Abstractions.INotificationBehavior<{notificationType}>>(_provider));");
        AppendLine(builder, 3, $"foreach (global::RA.Utilities.Feature.Abstractions.INotificationHandler<{notificationType}> handler in handlers)");
        AppendLine(builder, 3, "{");
        AppendLine(builder, 4, "try");
        AppendLine(builder, 4, "{");

        if (hasContext)
        {
            AppendLine(builder, 5, "global::RA.Utilities.Feature.Models.NotificationHandlerContextDelegate<TContext> handlerDelegate = c => handler.HandleAsync<TContext>(notification, c, cancellationToken);");
        }
        else
        {
            AppendLine(builder, 5, "global::RA.Utilities.Feature.Models.NotificationHandlerDelegate handlerDelegate = () => handler.HandleAsync(notification, cancellationToken);");
        }

        AppendLine(builder, 5, "for (int i = behaviors.Count - 1; i >= 0; i--)");
        AppendLine(builder, 5, "{");
        AppendLine(builder, 6, $"global::RA.Utilities.Feature.Abstractions.INotificationBehavior<{notificationType}> behavior = behaviors[i];");
        AppendLine(builder, 6, hasContext
            ? "global::RA.Utilities.Feature.Models.NotificationHandlerContextDelegate<TContext> previous = handlerDelegate;"
            : "global::RA.Utilities.Feature.Models.NotificationHandlerDelegate previous = handlerDelegate;");
        AppendLine(builder, 6, hasContext
            ? "handlerDelegate = c => behavior.HandleAsync<TContext>(notification, previous, c, cancellationToken);"
            : "handlerDelegate = () => behavior.HandleAsync(notification, previous, cancellationToken);");
        AppendLine(builder, 5, "}");

        if (hasContext)
        {
            AppendLine(builder, 5, "if (behaviors.Count == 0) { await handler.HandleAsync<TContext>(notification, ctx, cancellationToken); }");
            AppendLine(builder, 5, "else { await handlerDelegate(ctx); }");
        }
        else
        {
            AppendLine(builder, 5, "if (behaviors.Count == 0) { await handler.HandleAsync(notification, cancellationToken); }");
            AppendLine(builder, 5, "else { await handlerDelegate(); }");
        }

        AppendLine(builder, 4, "}");
        AppendLine(builder, 4, "catch (global::System.Exception ex)");
        AppendLine(builder, 4, "{");
        AppendLine(builder, 5, $"global::Microsoft.Extensions.Logging.LoggerExtensions.LogError(_logger, ex, \"[Publish] Handler {{HandlerType}} failed for notification {{NotificationType}}. Notification: {{@Notification}}\", handler.GetType().Name, typeof({notificationType}).Name, notification);");
        AppendLine(builder, 4, "}");
        AppendLine(builder, 3, "}");
    }

    // ------------------- monomorphic overloads -------------------

    private static void AppendResponseSend(StringBuilder builder, MessageModel message, string handlerFullyQualifiedName)
    {
        string messageType = message.MessageFullyQualifiedName;
        string responseType = message.ResponseFullyQualifiedName!;
        string handlerServiceType = handlerFullyQualifiedName.Length > 0
            ? handlerFullyQualifiedName
            : $"global::RA.Utilities.Feature.Abstractions.IRequestHandler<{messageType}, {responseType}>";

        AppendLine(builder, 2, $"public global::System.Threading.Tasks.Task<{responseType}> Send({messageType} request, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "{");
        AppendRequestSendBody(builder, messageType, responseType, RequestNullCheck(message), handlerServiceType, useInterfaceBehaviorCast: false);
        AppendLine(builder, 2, "}");
    }

    private static void AppendResponseContextSend(StringBuilder builder, MessageModel message, string handlerFullyQualifiedName)
    {
        string messageType = message.MessageFullyQualifiedName;
        string responseType = message.ResponseFullyQualifiedName!;
        string handlerServiceType = handlerFullyQualifiedName.Length > 0
            ? handlerFullyQualifiedName
            : $"global::RA.Utilities.Feature.Abstractions.IRequestHandler<{messageType}, {responseType}>";

        AppendLine(builder, 2, $"public global::System.Threading.Tasks.Task<{responseType}> Send<TContext>({messageType} request, global::RA.Utilities.Feature.Models.PipelineContext<TContext>? context = null, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "    where TContext : class, new()");
        AppendLine(builder, 2, "{");
        string handlerContextCall = handlerFullyQualifiedName.Length > 0
            ? $"((global::RA.Utilities.Feature.Abstractions.IRequestHandler<{messageType}, {responseType}>)handler).HandleAsync<TContext>(request, c, cancellationToken)"
            : "handler.HandleAsync<TContext>(request, c, cancellationToken)";
        AppendRequestContextSendBody(builder, messageType, responseType, RequestNullCheck(message), handlerServiceType, handlerContextCall, useInterfaceBehaviorCast: false);
        AppendLine(builder, 2, "}");
    }

    private static void AppendVoidSend(StringBuilder builder, MessageModel message, string handlerFullyQualifiedName)
    {
        string messageType = message.MessageFullyQualifiedName;
        string handlerServiceType = handlerFullyQualifiedName.Length > 0
            ? handlerFullyQualifiedName
            : $"global::RA.Utilities.Feature.Abstractions.IRequestHandler<{messageType}>";

        AppendLine(builder, 2, $"public global::System.Threading.Tasks.Task Send({messageType} request, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "{");
        AppendVoidSendBody(builder, messageType, RequestNullCheck(message), handlerServiceType, useInterfaceBehaviorCast: false);
        AppendLine(builder, 2, "}");
    }

    private static void AppendVoidContextSend(StringBuilder builder, MessageModel message, string handlerFullyQualifiedName)
    {
        string messageType = message.MessageFullyQualifiedName;
        string handlerServiceType = handlerFullyQualifiedName.Length > 0
            ? handlerFullyQualifiedName
            : $"global::RA.Utilities.Feature.Abstractions.IRequestHandler<{messageType}>";

        AppendLine(builder, 2, $"public global::System.Threading.Tasks.Task Send<TContext>({messageType} request, global::RA.Utilities.Feature.Models.PipelineContext<TContext>? context = null, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "    where TContext : class, new()");
        AppendLine(builder, 2, "{");
        string handlerContextCall = handlerFullyQualifiedName.Length > 0
            ? $"((global::RA.Utilities.Feature.Abstractions.IRequestHandler<{messageType}>)handler).HandleAsync<TContext>(request, c, cancellationToken)"
            : "handler.HandleAsync<TContext>(request, c, cancellationToken)";
        AppendVoidContextSendBody(builder, messageType, RequestNullCheck(message), handlerServiceType, handlerContextCall, useInterfaceBehaviorCast: false);
        AppendLine(builder, 2, "}");
    }

    private static void AppendPublish(StringBuilder builder, MessageModel message)
    {
        string messageType = message.MessageFullyQualifiedName;

        AppendLine(builder, 2, $"public async global::System.Threading.Tasks.Task Publish({messageType} notification, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "{");
        AppendNotificationNullCheck(builder, message);
        AppendPublishBody(builder, messageType, hasContext: false);
        AppendLine(builder, 2, "}");
    }

    private static void AppendContextPublish(StringBuilder builder, MessageModel message)
    {
        string messageType = message.MessageFullyQualifiedName;

        AppendLine(builder, 2, $"public async global::System.Threading.Tasks.Task Publish<TContext>({messageType} notification, global::RA.Utilities.Feature.Models.PipelineContext<TContext>? context = null, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "    where TContext : class, new()");
        AppendLine(builder, 2, "{");
        AppendNotificationNullCheck(builder, message);
        AppendLine(builder, 3, "global::RA.Utilities.Feature.Models.PipelineContext<TContext> ctx = context ?? new global::RA.Utilities.Feature.Models.PipelineContext<TContext>();");
        AppendPublishBody(builder, messageType, hasContext: true);
        AppendLine(builder, 2, "}");
    }

    private static string RequestNullCheck(MessageModel message) =>
        message.MessageIsValueType
            ? string.Empty
            : "if (request is null) { throw new global::System.ArgumentNullException(nameof(request)); }";

    // ------------------- object-based dispatch -------------------

    private static void AppendObjectSend(StringBuilder builder, EquatableArray<MessageModel> responseMessages, EquatableArray<MessageModel> voidMessages, bool useDictionaries)
    {
        AppendLine(builder, 2, "public global::System.Threading.Tasks.Task<object?> Send(object request, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (request is null) { throw new global::System.ArgumentNullException(nameof(request)); }");
        AppendLine(builder, 3, "global::System.Type requestType = request.GetType();");

        if (useDictionaries)
        {
            AppendLine(builder, 3, "if (s_sendObject.TryGetValue(requestType, out global::System.Func<Mediator, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>> sender))");
            AppendLine(builder, 3, "{");
            AppendLine(builder, 4, "return sender(this, request, cancellationToken);");
            AppendLine(builder, 3, "}");
        }
        else
        {
            foreach (MessageModel message in responseMessages)
            {
                AppendLine(builder, 3, $"if (requestType == typeof({message.MessageFullyQualifiedName}))");
                AppendLine(builder, 3, "{");
                AppendLine(builder, 4, $"global::System.Threading.Tasks.Task<{message.ResponseFullyQualifiedName}> task = Send(({message.MessageFullyQualifiedName})request, cancellationToken);");
                AppendLine(builder, 4, message.ResponseIsValueType
                    ? "return BoxAsync(task);"
                    : $"return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.Task<{message.ResponseFullyQualifiedName}>, global::System.Threading.Tasks.Task<object?>>(ref task);");
                AppendLine(builder, 3, "}");
            }

            foreach (MessageModel message in voidMessages)
            {
                AppendLine(builder, 3, $"if (requestType == typeof({message.MessageFullyQualifiedName}))");
                AppendLine(builder, 3, "{");
                AppendLine(builder, 4, $"return ToObjectTaskAsync(Send(({message.MessageFullyQualifiedName})request, cancellationToken));");
                AppendLine(builder, 3, "}");
            }
        }

        AppendLine(builder, 3, "throw new global::RA.Utilities.Feature.Exceptions.HandlerNotFoundException(requestType);");
        AppendLine(builder, 2, "}");
    }

    private static void AppendObjectPublish(StringBuilder builder, EquatableArray<MessageModel> notifications, bool useDictionaries)
    {
        AppendLine(builder, 2, "public global::System.Threading.Tasks.Task Publish(object notification, global::System.Threading.CancellationToken cancellationToken = default)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (notification is null) { throw new global::System.ArgumentNullException(nameof(notification)); }");
        AppendLine(builder, 3, "global::System.Type notificationType = notification.GetType();");

        if (useDictionaries)
        {
            AppendLine(builder, 3, "if (s_publish.TryGetValue(notificationType, out global::System.Func<Mediator, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> publisher))");
            AppendLine(builder, 3, "{");
            AppendLine(builder, 4, "return publisher(this, notification, cancellationToken);");
            AppendLine(builder, 3, "}");
        }
        else
        {
            foreach (MessageModel message in notifications)
            {
                AppendLine(builder, 3, $"if (notificationType == typeof({message.MessageFullyQualifiedName}))");
                AppendLine(builder, 3, "{");
                AppendLine(builder, 4, $"return Publish(({message.MessageFullyQualifiedName})notification, cancellationToken);");
                AppendLine(builder, 3, "}");
            }
        }

        AppendLine(builder, 3, "throw new global::RA.Utilities.Feature.Exceptions.HandlerNotFoundException(notificationType);");
        AppendLine(builder, 2, "}");
    }

    // ------------------- IMediator interface implementations -------------------

    private static void AppendVoidInterfaceSend(StringBuilder builder)
    {
        AppendLine(builder, 2, "global::System.Threading.Tasks.Task global::RA.Utilities.Feature.Abstractions.IMediator.Send<TRequest>(TRequest request, global::System.Threading.CancellationToken cancellationToken)");
        AppendLine(builder, 2, "{");
        AppendVoidSendBody(builder, "TRequest", "if (request is null) { throw new global::System.ArgumentNullException(nameof(request)); }", "global::RA.Utilities.Feature.Abstractions.IRequestHandler<TRequest>", useInterfaceBehaviorCast: true);
        AppendLine(builder, 2, "}");
    }

    private static void AppendResponseInterfaceSend(StringBuilder builder)
    {
        AppendLine(builder, 2, "global::System.Threading.Tasks.Task<TResponse> global::RA.Utilities.Feature.Abstractions.IMediator.Send<TRequest, TResponse>(TRequest request, global::System.Threading.CancellationToken cancellationToken)");
        AppendLine(builder, 2, "{");
        AppendRequestSendBody(builder, "TRequest", "TResponse", "if (request is null) { throw new global::System.ArgumentNullException(nameof(request)); }", "global::RA.Utilities.Feature.Abstractions.IRequestHandler<TRequest, TResponse>", useInterfaceBehaviorCast: true);
        AppendLine(builder, 2, "}");
    }

    private static void AppendVoidContextInterfaceSend(StringBuilder builder)
    {
        AppendLine(builder, 2, "global::System.Threading.Tasks.Task global::RA.Utilities.Feature.Abstractions.IMediator.Send<TRequest, TContext>(TRequest request, global::RA.Utilities.Feature.Models.PipelineContext<TContext>? context, global::System.Threading.CancellationToken cancellationToken)");
        AppendLine(builder, 2, "{");
        AppendVoidContextSendBody(builder, "TRequest", "if (request is null) { throw new global::System.ArgumentNullException(nameof(request)); }", "global::RA.Utilities.Feature.Abstractions.IRequestHandler<TRequest>", "handler.HandleAsync<TContext>(request, c, cancellationToken)", useInterfaceBehaviorCast: true);
        AppendLine(builder, 2, "}");
    }

    private static void AppendResponseContextInterfaceSend(StringBuilder builder)
    {
        AppendLine(builder, 2, "global::System.Threading.Tasks.Task<TResponse> global::RA.Utilities.Feature.Abstractions.IMediator.Send<TRequest, TResponse, TContext>(TRequest request, global::RA.Utilities.Feature.Models.PipelineContext<TContext>? context, global::System.Threading.CancellationToken cancellationToken)");
        AppendLine(builder, 2, "{");
        AppendRequestContextSendBody(builder, "TRequest", "TResponse", "if (request is null) { throw new global::System.ArgumentNullException(nameof(request)); }", "global::RA.Utilities.Feature.Abstractions.IRequestHandler<TRequest, TResponse>", "handler.HandleAsync<TContext>(request, c, cancellationToken)", useInterfaceBehaviorCast: true);
        AppendLine(builder, 2, "}");
    }

    private static void AppendPublishInterface(StringBuilder builder)
    {
        AppendLine(builder, 2, "async global::System.Threading.Tasks.Task global::RA.Utilities.Feature.Abstractions.IMediator.Publish<TNotification>(TNotification notification, global::System.Threading.CancellationToken cancellationToken)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (notification is null) { throw new global::System.ArgumentNullException(nameof(notification)); }");
        AppendPublishBody(builder, "TNotification", hasContext: false);
        AppendLine(builder, 2, "}");
    }

    private static void AppendContextPublishInterface(StringBuilder builder)
    {
        AppendLine(builder, 2, "async global::System.Threading.Tasks.Task global::RA.Utilities.Feature.Abstractions.IMediator.Publish<TNotification, TContext>(TNotification notification, global::RA.Utilities.Feature.Models.PipelineContext<TContext>? context, global::System.Threading.CancellationToken cancellationToken)");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, "if (notification is null) { throw new global::System.ArgumentNullException(nameof(notification)); }");
        AppendLine(builder, 3, "global::RA.Utilities.Feature.Models.PipelineContext<TContext> ctx = context ?? new global::RA.Utilities.Feature.Models.PipelineContext<TContext>();");
        AppendPublishBody(builder, "TNotification", hasContext: true);
        AppendLine(builder, 2, "}");
    }

    // ------------------- fast dictionaries (object dispatch above the size threshold) -------------------

    private static void AppendObjectSendDictionary(StringBuilder builder, EquatableArray<MessageModel> responseMessages, EquatableArray<MessageModel> voidMessages)
    {
        AppendLine(builder, 2, "private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<Mediator, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>>> s_sendObject =");
        AppendLine(builder, 3, "new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<Mediator, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<object?>>>()");
        AppendLine(builder, 2, "{");

        foreach (MessageModel message in responseMessages)
        {
            AppendLine(builder, 3, $"[typeof({message.MessageFullyQualifiedName})] = static (impl, request, cancellationToken) =>");
            AppendLine(builder, 3, "{");
            AppendLine(builder, 4, $"global::System.Threading.Tasks.Task<{message.ResponseFullyQualifiedName}> task = impl.Send(({message.MessageFullyQualifiedName})request, cancellationToken);");
            AppendLine(builder, 4, message.ResponseIsValueType
                ? "return BoxAsync(task);"
                : $"return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.Task<{message.ResponseFullyQualifiedName}>, global::System.Threading.Tasks.Task<object?>>(ref task);");
            AppendLine(builder, 3, "},");
        }

        foreach (MessageModel message in voidMessages)
        {
            AppendLine(builder, 3, $"[typeof({message.MessageFullyQualifiedName})] = static async (impl, request, cancellationToken) =>");
            AppendLine(builder, 3, "{");
            AppendLine(builder, 4, $"await impl.Send(({message.MessageFullyQualifiedName})request, cancellationToken);");
            AppendLine(builder, 4, "return null;");
            AppendLine(builder, 3, "},");
        }

        AppendLine(builder, 2, "};");
    }

    private static void AppendPublishDictionary(StringBuilder builder, EquatableArray<MessageModel> notifications)
    {
        AppendLine(builder, 2, "private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<Mediator, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> s_publish =");
        AppendLine(builder, 3, "new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<Mediator, object, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>>()");
        AppendLine(builder, 2, "{");

        foreach (MessageModel message in notifications)
        {
            AppendLine(builder, 3, $"[typeof({message.MessageFullyQualifiedName})] = static (impl, notification, cancellationToken) => impl.Publish(({message.MessageFullyQualifiedName})notification, cancellationToken),");
        }

        AppendLine(builder, 2, "};");
    }

    private static void AppendHelpers(StringBuilder builder, bool needsBoxAsync, bool needsToObjectTaskAsync)
    {
        if (needsBoxAsync)
        {
            AppendLine(builder, 2, "private static async global::System.Threading.Tasks.Task<object?> BoxAsync<T>(global::System.Threading.Tasks.Task<T> task)");
            AppendLine(builder, 2, "{");
            AppendLine(builder, 3, "return await task;");
            AppendLine(builder, 2, "}");
        }

        if (needsToObjectTaskAsync)
        {
            AppendLine(builder, 2, "private static async global::System.Threading.Tasks.Task<object?> ToObjectTaskAsync(global::System.Threading.Tasks.Task task)");
            AppendLine(builder, 2, "{");
            AppendLine(builder, 3, "await task;");
            AppendLine(builder, 3, "return null;");
            AppendLine(builder, 2, "}");
        }
    }

    private static void AppendInitializer(StringBuilder builder)
    {
        AppendLine(builder, 1, "internal static class MediatorRegistrationInitializer");
        AppendLine(builder, 1, "{");
        AppendLine(builder, 2, "[global::System.Runtime.CompilerServices.ModuleInitializer]");
        AppendLine(builder, 2, "internal static void Initialize()");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, $"global::{KnownMetadataNames.MediatorRegistrationsMetadataName}.{KnownMetadataNames.AddMethod}(static services =>");
        AppendLine(builder, 3, "{");
        AppendLine(builder, 4, "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<Mediator>(services);");
        AppendLine(builder, 4, "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::RA.Utilities.Feature.Abstractions.IMediator>(services, static provider => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Mediator>(provider));");
        AppendLine(builder, 3, "});");
        AppendLine(builder, 2, "}");
        AppendLine(builder, 1, "}");
    }

    private static void AppendNotificationNullCheck(StringBuilder builder, MessageModel message)
    {
        if (!message.MessageIsValueType)
        {
            AppendLine(builder, 3, "if (notification is null) { throw new global::System.ArgumentNullException(nameof(notification)); }");
        }
    }

    private static void AppendLine(StringBuilder builder, int depth, string text) =>
        builder.Append(' ', depth * 4).Append(text).Append('\n');
}
