using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RA.Utilities.Feature.Generators.Models;

namespace RA.Utilities.Feature.Generators;

/// <summary>
/// Builds the generated module initializer that queues handler registrations, and reports the
/// per-type and duplicate-handler diagnostics.
/// </summary>
internal static class SourceEmitter
{
    /// <summary>
    /// The standard header for generated files. The <c>auto-generated</c> marker makes analyzers skip
    /// the file, and the pragma silences compiler warnings (such as CS1591) in consumer projects
    /// that build with warnings as errors.
    /// </summary>
    private const string GeneratedFileHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

    /// <summary>
    /// The hint name of the generated source file.
    /// </summary>
    private const string HintName = "RA.Utilities.Feature.HandlerRegistrations.g.cs";

    /// <summary>
    /// Emits the generated module initializer and reports validation diagnostics for the discovered
    /// handler models.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="models">The discovered handler models.</param>
    public static void Emit(SourceProductionContext context, EquatableArray<HandlerModel> models)
    {
        // Partial declarations yield one model per part; deduplicate on the model's value equality
        // (which deliberately excludes the location).
        models = Sort(models.Distinct());

        ReportTypeValidation(context, models);
        ReportDuplicateRequestHandlers(context, models);

        EquatableArray<HandlerModel> registrations = models.Where(model => !model.IsDiagnostic).ToImmutableArray();
        if (registrations.IsDefaultOrEmpty)
        {
            return;
        }

        context.AddSource(HintName, SourceText.From(BuildSource(registrations), Encoding.UTF8));
    }

    /// <summary>
    /// Reports the per-type diagnostics (generic types, inaccessible types, struct handlers)
    /// attached to the discovered models, deduplicated across partial declarations.
    /// </summary>
    private static void ReportTypeValidation(SourceProductionContext context, EquatableArray<HandlerModel> models)
    {
        var reported = new HashSet<string>(StringComparer.Ordinal);

        foreach (HandlerModel model in models)
        {
            if (model.Diagnostic is not DiagnosticModel diagnostic)
            {
                continue;
            }

            string key = diagnostic.Descriptor.Id + "|" + model.TypeName;
            if (!reported.Add(key))
            {
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                diagnostic.Descriptor,
                diagnostic.Location,
                diagnostic.Arguments));
        }
    }

    /// <summary>
    /// Reports <c>FEAG005</c> for every request handler pair (request/response or void request)
    /// implemented by more than one class in the assembly. Notifications are exempt because
    /// fan-out is their purpose.
    /// </summary>
    private static void ReportDuplicateRequestHandlers(SourceProductionContext context, EquatableArray<HandlerModel> models)
    {
        foreach (IGrouping<string, HandlerModel> duplicate in models
            .Where(model => !model.IsDiagnostic && model.Kind != HandlerKind.Notification)
            .GroupBy(model => model.InterfaceFullyQualifiedName, StringComparer.Ordinal)
            .Where(grouping => grouping.Count() > 1))
        {
            foreach (HandlerModel model in duplicate.Skip(1))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.DuplicateRequestHandler,
                    model.Location,
                    model.TypeName,
                    duplicate.Key));
            }
        }
    }

    private static EquatableArray<HandlerModel> Sort(IEnumerable<HandlerModel> models) =>
        models
            .OrderBy(model => model.InterfaceFullyQualifiedName, StringComparer.Ordinal)
            .ThenBy(model => model.HandlerFullyQualifiedName, StringComparer.Ordinal)
            .ToImmutableArray();

    private static string BuildSource(EquatableArray<HandlerModel> models)
    {
        var builder = new StringBuilder();
        builder.Append(GeneratedFileHeader);
        builder.Append("namespace ").Append(KnownMetadataNames.GeneratedNamespace).Append('\n');
        builder.Append("{\n");
        AppendLine(builder, 1, $"internal static class {KnownMetadataNames.InitializerClassName}");
        AppendLine(builder, 1, "{");
        AppendLine(builder, 2, "[global::System.Runtime.CompilerServices.ModuleInitializer]");
        AppendLine(builder, 2, "internal static void Initialize()");
        AppendLine(builder, 2, "{");
        AppendLine(builder, 3, $"global::{KnownMetadataNames.HandlerRegistrationsMetadataName}.{KnownMetadataNames.AddMethod}(static services =>");
        AppendLine(builder, 3, "{");

        foreach (HandlerModel model in models)
        {
            string addMethod = model.Kind == HandlerKind.Notification ? "AddTransient" : "AddScoped";
            AppendLine(builder, 4, $"{KnownMetadataNames.ServiceCollectionServiceExtensions}.{addMethod}<{model.InterfaceFullyQualifiedName}, {model.HandlerFullyQualifiedName}>(services);");
        }

        AppendLine(builder, 3, "});");
        AppendLine(builder, 2, "}");
        AppendLine(builder, 1, "}");
        builder.Append("}\n");

        return builder.ToString();
    }

    private static void AppendLine(StringBuilder builder, int depth, string text) =>
        builder.Append(' ', depth * 4).Append(text).Append('\n');
}
