using System.Collections.Immutable;
using System.Linq;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using RA.Utilities.Api.Generators;

namespace RA.Utilities.Api.Tests.Generators;

/// <summary>
/// Contains unit tests for the <see cref="EndpointRegistrationGenerator"/> incremental source generator.
/// </summary>
public class EndpointRegistrationGeneratorTests
{
    /// <summary>
    /// A typical endpoint assembly: two groups and several endpoints spread across them.
    /// </summary>
    private const string TypicalSources = """
        using Microsoft.AspNetCore.Builder;

        namespace Sample;

        internal sealed class TodosGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
        {
            public static string GroupName => "Todos";
            public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
        }

        internal sealed class UsersGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
        {
            public static string GroupName => "Users";
            public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/users");
        }

        internal sealed class GetTodosEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
        {
            public static string GroupName => "Todos";
            public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapGet("/", () => "[]");
        }

        internal sealed class CreateTodoEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
        {
            public static string GroupName => "Todos";
            public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapPost("/", () => "created");
        }

        internal sealed class GetUsersEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
        {
            public static string GroupName => "Users";
            public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapGet("/", () => "[]");
        }

        internal sealed class GetUserByIdEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
        {
            public static string GroupName => "Users";
            public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapGet("/{id:int}", (int id) => $"user-{id}");
        }
        """;

    /// <summary>
    /// The exact expected output for <see cref="TypicalSources"/>.
    /// </summary>
    private const string TypicalExpectedSource = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable

        namespace RA.Utilities.Api.Extensions
        {
            public static partial class HttpEndpointServiceCollectionExtensions
            {
                public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)
                {
                    global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups = new global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder>();

                    AddGroup(groups, global::Sample.TodosGroup.GroupName, global::Sample.TodosGroup.MapGroup(builder));
                    AddGroup(groups, global::Sample.UsersGroup.GroupName, global::Sample.UsersGroup.MapGroup(builder));

                    global::Sample.CreateTodoEndpoint.MapEndpoint(GetGroup(groups, "CreateTodoEndpoint", global::Sample.CreateTodoEndpoint.GroupName));
                    global::Sample.GetTodosEndpoint.MapEndpoint(GetGroup(groups, "GetTodosEndpoint", global::Sample.GetTodosEndpoint.GroupName));
                    global::Sample.GetUserByIdEndpoint.MapEndpoint(GetGroup(groups, "GetUserByIdEndpoint", global::Sample.GetUserByIdEndpoint.GroupName));
                    global::Sample.GetUsersEndpoint.MapEndpoint(GetGroup(groups, "GetUsersEndpoint", global::Sample.GetUsersEndpoint.GroupName));
                    return builder;
                }

                private static void AddGroup(global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups, string groupName, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder group)
                {
                    if (groups.ContainsKey(groupName))
                    {
                        throw new global::System.InvalidOperationException("Multiple IEndpointGroup implementations declare the GroupName '" + groupName + "'. Group names must be unique within the assembly.");
                    }

                    groups.Add(groupName, group);
                }

                private static global::Microsoft.AspNetCore.Routing.RouteGroupBuilder GetGroup(global::System.Collections.Generic.Dictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups, string endpointTypeName, string groupName)
                {
                    if (!groups.TryGetValue(groupName, out global::Microsoft.AspNetCore.Routing.RouteGroupBuilder? group))
                    {
                        throw new global::System.InvalidOperationException("Endpoint '" + endpointTypeName + "' references endpoint group '" + groupName + "', but no IEndpointGroup with that GroupName is registered.");
                    }

                    return group;
                }
            }
        }
        """;

    /// <summary>
    /// Verifies that a typical assembly of groups and endpoints produces exactly the expected
    /// registration source, with groups mapped before any endpoint and no diagnostics.
    /// </summary>
    [Fact]
    public void TypicalGroupsAndEndpoints_ShouldGenerateExpectedRegistrationSource()
    {
        // Arrange & Act
        (Compilation outputCompilation, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            TypicalSources);

        // Assert
        runResult.Results.Should().ContainSingle()
            .Which.GeneratedSources.Should().ContainSingle()
            .Which.HintName.Should().Be("RA.Utilities.Api.EndpointRegistrations.g.cs");

        string generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();
        generatedSource.TrimEnd().Should().Be(TypicalExpectedSource.TrimEnd());

        runResult.Results[0].Diagnostics.Should().BeEmpty();
        outputCompilation.GetDiagnostics().Should().NotContain(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    /// <summary>
    /// Verifies that a compilation without any endpoint types still generates a callable (empty)
    /// registration method.
    /// </summary>
    [Fact]
    public void NoEndpointTypes_ShouldGenerateEmptyRegistrationMethod()
    {
        // Arrange & Act
        (Compilation outputCompilation, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources);

        // Assert
        string generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        generatedSource.Should().Contain("return builder;");
        generatedSource.Should().NotContain("AddGroup");
        generatedSource.Should().NotContain("GetGroup");

        runResult.Results[0].Diagnostics.Should().BeEmpty();
        outputCompilation.GetDiagnostics().Should().NotContain(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    /// <summary>
    /// Verifies that nested internal classes are referenced with their full containing path.
    /// </summary>
    [Fact]
    public void NestedInternalClasses_ShouldBeRegisteredWithFullPath()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            public static class Api
            {
                internal sealed class TodosGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
                {
                    public static string GroupName => "Todos";
                    public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
                }

                internal sealed class GetTodosEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
                {
                    public static string GroupName => "Todos";
                    public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapGet("/", () => "[]");
                }
            }
            """;

        // Act
        (Compilation outputCompilation, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        string generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        generatedSource.Should().Contain("AddGroup(groups, global::Sample.Api.TodosGroup.GroupName, global::Sample.Api.TodosGroup.MapGroup(builder));");
        generatedSource.Should().Contain("global::Sample.Api.GetTodosEndpoint.MapEndpoint(GetGroup(groups, \"GetTodosEndpoint\", global::Sample.Api.GetTodosEndpoint.GroupName));");

        runResult.Results[0].Diagnostics.Should().BeEmpty();
        outputCompilation.GetDiagnostics().Should().NotContain(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    /// <summary>
    /// Verifies that types implementing the contract only through a base class are not registered
    /// again (the base class itself is).
    /// </summary>
    [Fact]
    public void TypesInheritingContract_ShouldNotBeRegisteredTwice()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            internal class BaseGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
            {
                public static string GroupName => "Base";
                public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/base");
            }

            internal sealed class DerivedGroup : BaseGroup
            {
            }
            """;

        // Act
        (Compilation _, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        string generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        generatedSource.Should().Contain("global::Sample.BaseGroup.MapGroup(builder)");
        generatedSource.Should().NotContain("DerivedGroup");
    }

    /// <summary>
    /// Verifies that two groups declaring the same constant name are reported with EPMG001 on both types.
    /// </summary>
    [Fact]
    public void DuplicateGroupNames_ShouldReportDiagnosticOnBothGroups()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            internal sealed class FirstTodosGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
            {
                public static string GroupName => "Todos";
                public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
            }

            internal sealed class SecondTodosGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
            {
                public static string GroupName => "Todos";
                public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
            }
            """;

        // Act
        (Compilation _, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        ImmutableArray<Diagnostic> diagnostics = runResult.Results[0].Diagnostics;
        diagnostics.Should().HaveCount(2)
            .And.OnlyContain(diagnostic => diagnostic.Id == "EPMG001");
        diagnostics.Select(diagnostic => diagnostic.GetMessage())
            .Should().Contain(message => message.Contains("FirstTodosGroup"))
            .And.Contain(message => message.Contains("SecondTodosGroup"));

        // The registration source is still generated; the compiler fails on the diagnostics instead.
        runResult.Results[0].GeneratedSources.Should().ContainSingle();
    }

    /// <summary>
    /// Verifies that an endpoint referencing a group name no group declares is reported with EPMG002.
    /// </summary>
    [Fact]
    public void EndpointReferencingUnknownGroup_ShouldReportDiagnostic()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            internal sealed class GetTodosEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
            {
                public static string GroupName => "Missing";
                public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapGet("/", () => "[]");
            }
            """;

        // Act
        (Compilation _, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        ImmutableArray<Diagnostic> diagnostics = runResult.Results[0].Diagnostics;
        diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be("EPMG002");
        diagnostics[0].GetMessage().Should().Contain("GetTodosEndpoint").And.Contain("Missing");
    }

    /// <summary>
    /// Verifies that a generic implementation is reported with EPMG003.
    /// </summary>
    [Fact]
    public void GenericImplementation_ShouldReportDiagnostic()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            internal sealed class GenericGroup<T> : RA.Utilities.Api.Abstractions.IEndpointGroup
            {
                public static string GroupName => "Todos";
                public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
            }
            """;

        // Act
        (Compilation _, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        runResult.Results[0].Diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be("EPMG003");
    }

    /// <summary>
    /// Verifies that a private nested implementation is reported with EPMG004.
    /// </summary>
    [Fact]
    public void PrivateNestedImplementation_ShouldReportDiagnostic()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            public static class Api
            {
                private sealed class HiddenGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
                {
                    public static string GroupName => "Todos";
                    public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
                }
            }
            """;

        // Act
        (Compilation _, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        runResult.Results[0].Diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be("EPMG004");
    }

    /// <summary>
    /// Verifies that an implementation using explicit static interface implementations is reported
    /// with EPMG005, because the generated code cannot invoke those members.
    /// </summary>
    [Fact]
    public void ExplicitStaticImplementation_ShouldReportDiagnostic()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            internal sealed class ExplicitGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
            {
                static string RA.Utilities.Api.Abstractions.IEndpointGroup.GroupName => "Todos";
                static Microsoft.AspNetCore.Routing.RouteGroupBuilder RA.Utilities.Api.Abstractions.IEndpointGroup.MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
            }
            """;

        // Act
        (Compilation _, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        runResult.Results[0].Diagnostics.Should().ContainSingle()
            .Which.Id.Should().Be("EPMG005");
    }

    /// <summary>
    /// Verifies that non-constant group names are not validated at compile time: the generated code
    /// calls the <c>GroupName</c> property itself, so the name is resolved at runtime.
    /// </summary>
    [Fact]
    public void ComputedGroupNames_ShouldNotBeValidatedAtCompileTime()
    {
        // Arrange
        const string source = """
            using Microsoft.AspNetCore.Builder;

            namespace Sample;

            internal sealed class TodosGroup : RA.Utilities.Api.Abstractions.IEndpointGroup
            {
                public static string GroupName => typeof(TodosGroup).Name;
                public static Microsoft.AspNetCore.Routing.RouteGroupBuilder MapGroup(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app) => app.MapGroup("api/todos");
            }

            internal sealed class GetTodosEndpoint : RA.Utilities.Api.Abstractions.IEndpoint
            {
                public static string GroupName => typeof(TodosGroup).Name;
                public static void MapEndpoint(Microsoft.AspNetCore.Routing.RouteGroupBuilder group) => group.MapGet("/", () => "[]");
            }
            """;

        // Act
        (Compilation outputCompilation, GeneratorDriverRunResult runResult) = GeneratorTestHost.RunGenerator(
            GeneratorTestHost.RuntimeSources,
            source);

        // Assert
        string generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        generatedSource.Should().Contain("global::Sample.TodosGroup.GroupName");
        generatedSource.Should().Contain("global::Sample.GetTodosEndpoint.GroupName");

        runResult.Results[0].Diagnostics.Should().BeEmpty();
        outputCompilation.GetDiagnostics().Should().NotContain(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }
}
