<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<Version>10.0.1</Version>
		<Title>RA Utilities Application Validation</Title>
    <Description>RA.Utilities.Application.Validation provides reusable validators and helpers built on FluentValidation for validating incoming requests. It aggregates multiple validators asynchronously and converts FluentValidation failures into structured BadRequestException/ValidationError results.</Description>
    <PackageTags>RA;Utilities;Application;Validation;FluentValidation;Validators;ErrorHandling</PackageTags>
    <PackageId>RA.Utilities.Application.Validation</PackageId>
		<PackageIcon>validation.png</PackageIcon>
		<PackageReleaseNotesFile>releasenotes.md</PackageReleaseNotesFile>
    <AssemblyTitle>RA.Utilities.Application.Validation</AssemblyTitle>
	</PropertyGroup>

  <ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="../../Assets/Images/validation.png" Pack="true" PackagePath="\" />
		<None Include="releasenotes.md" Pack="true" PackagePath="\" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Core/RA.Utilities.Core.Exceptions/RA.Utilities.Core.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions/" />
  </ItemGroup>

</Project>
