using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using RA.Utilities.Integrations.Generators.Models;

namespace RA.Utilities.Integrations.Generators;

/// <summary>
/// Builds the generated partial declarations for query and header parameter classes.
/// </summary>
internal static class SourceEmitter
{
    /// <summary>
    /// The standard header for generated files. The <c>auto-generated</c> marker makes analyzers skip
    /// the file, and the pragma silences compiler warnings (such as CS1591) in consumer projects
    /// that build with warnings as errors.
    /// </summary>
    private const string GeneratedFileHeader = "// <auto-generated/>\n#pragma warning disable\n#nullable enable\n\n";

    /// <summary>
    /// Emits the generated partial declaration for the given model.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="model">The model describing the marked parameter class.</param>
    public static void Emit(SourceProductionContext context, RequestModel model)
    {
        string suffix = model.ParameterKind == ParameterKind.Query ? "QueryParameters.g.cs" : "HeaderParameters.g.cs";
        string hintName = string.IsNullOrEmpty(model.Namespace)
            ? $"{model.TypeName}.{suffix}"
            : $"{model.Namespace}.{model.TypeName}.{suffix}";

        context.AddSource(hintName, SourceText.From(BuildSource(model), Encoding.UTF8));
    }

    private static string BuildSource(RequestModel model)
    {
        bool isQuery = model.ParameterKind == ParameterKind.Query;
        string interfaceName = isQuery ? KnownMetadataNames.IQueryStringRequest : KnownMetadataNames.IHeaderRequest;
        string formatterName = isQuery ? "FormatQueryParameterValue" : "FormatHeaderParameterValue";
        string keyFormatterName = isQuery ? "FormatQueryParameterKey" : "FormatHeaderParameterKey";
        bool hasDictionaryProperty = model.Properties.Any(property => property.Kind == PropertyKind.Dictionary);

        StringBuilder builder = new StringBuilder();
        builder.Append(GeneratedFileHeader);

        int depth = 0;

        if (model.Namespace is not null)
        {
            AppendLine(builder, depth, $"namespace {model.Namespace}");
            AppendLine(builder, depth, "{");
            depth++;
        }

        foreach (ContainingTypeModel container in model.ContainingTypes)
        {
            AppendLine(builder, depth, $"{TypeKeyword(container.IsRecord)} {container.Name}{TypeParameters(container.TypeParameters)}");
            AppendLine(builder, depth, "{");
            depth++;
        }

        AppendLine(builder, depth, $"{TypeKeyword(model.IsRecord)} {model.TypeName}{TypeParameters(model.TypeParameters)} : {interfaceName}");
        AppendLine(builder, depth, "{");
        depth++;

        AppendMappingMethod(builder, model, isQuery, formatterName, keyFormatterName, depth);
        AppendFormatter(builder, formatterName, depth);

        if (hasDictionaryProperty)
        {
            AppendKeyFormatter(builder, keyFormatterName, depth);
        }

        while (depth > 0)
        {
            depth--;
            AppendLine(builder, depth, "}");
        }

        return builder.ToString();
    }

    private static void AppendMappingMethod(
        StringBuilder builder,
        RequestModel model,
        bool isQuery,
        string formatterName,
        string keyFormatterName,
        int depth)
    {
        string methodSignature = isQuery
            ? $"public {KnownMetadataNames.QueryParams} {KnownMetadataNames.QueryStringValuesMethod}()"
            : $"public global::System.Collections.Generic.Dictionary<string, string> {KnownMetadataNames.ToHeadersMethod}()";
        string valuesInitialization = isQuery
            ? $"{KnownMetadataNames.QueryParams} values = new {KnownMetadataNames.QueryParams}();"
            : "global::System.Collections.Generic.Dictionary<string, string> values = new global::System.Collections.Generic.Dictionary<string, string>();";

        AppendLine(builder, depth, methodSignature);
        AppendLine(builder, depth, "{");
        depth++;

        AppendLine(builder, depth, valuesInitialization);

        foreach (PropertyModel property in model.Properties)
        {
            AppendPropertyMapping(builder, property, formatterName, keyFormatterName, isQuery, depth);
            builder.Append('\n');
        }

        AppendLine(builder, depth, "return values;");
        depth--;
        AppendLine(builder, depth, "}");

        if (isQuery)
        {
            // Default interface members are not callable on the class itself, so a convenience
            // overload is generated for class-typed call sites.
            builder.Append('\n');
            AppendLine(builder, depth, "public string ToQueryString(string action)");
            AppendLine(builder, depth, "{");
            AppendLine(builder, depth + 1, "return action + global::RA.Utilities.Integrations.Utilities.QueryUtilities.ToQueryString(QueryStringValues());");
            AppendLine(builder, depth, "}");
        }
    }

    private static void AppendPropertyMapping(
        StringBuilder builder,
        PropertyModel property,
        string formatterName,
        string keyFormatterName,
        bool isQuery,
        int depth)
    {
        string access = $"this.{EscapeIdentifier(property.Name)}";
        string camel = CamelCase(property.Name);

        void AddOrSet(StringBuilder target, int targetDepth, string key, string value)
        {
            if (isQuery)
            {
                AppendLine(target, targetDepth, $"values.Add({key}, {value});");
            }
            else
            {
                AppendLine(target, targetDepth, $"values[{key}] = {value};");
            }
        }

        switch (property.Kind)
        {
            case PropertyKind.Scalar:
                AppendLine(builder, depth, $"string? {camel}Value = {formatterName}({access});");
                AppendLine(builder, depth, $"if ({camel}Value is not null)");
                AppendLine(builder, depth, "{");
                AddOrSet(builder, depth + 1, $"\"{property.ParameterName}\"", $"{camel}Value");
                AppendLine(builder, depth, "}");
                break;

            case PropertyKind.Enumerable:
                AppendLine(builder, depth, $"var {camel}Sequence = {access};");
                AppendLine(builder, depth, $"if ({camel}Sequence is not null)");
                AppendLine(builder, depth, "{");
                AppendLine(builder, depth + 1, $"foreach (var {camel}Item in {camel}Sequence)");
                AppendLine(builder, depth + 1, "{");
                AppendLine(builder, depth + 2, $"string? {camel}Value = {formatterName}({camel}Item);");
                AppendLine(builder, depth + 2, $"if ({camel}Value is not null)");
                AppendLine(builder, depth + 2, "{");
                AddOrSet(builder, depth + 3, $"\"{property.ParameterName}\"", $"{camel}Value");
                AppendLine(builder, depth + 2, "}");
                AppendLine(builder, depth + 1, "}");
                AppendLine(builder, depth, "}");
                break;

            case PropertyKind.Dictionary:
                AppendLine(builder, depth, $"var {camel}Map = {access};");
                AppendLine(builder, depth, $"if ({camel}Map is not null)");
                AppendLine(builder, depth, "{");
                AppendLine(builder, depth + 1, $"foreach (var {camel}Entry in {camel}Map)");
                AppendLine(builder, depth + 1, "{");
                AppendLine(builder, depth + 2, $"string? {camel}Value = {formatterName}({camel}Entry.Value);");
                AppendLine(builder, depth + 2, $"if ({camel}Value is not null)");
                AppendLine(builder, depth + 2, "{");
                AddOrSet(builder, depth + 3, $"{keyFormatterName}({camel}Entry.Key)", $"{camel}Value");
                AppendLine(builder, depth + 2, "}");
                AppendLine(builder, depth + 1, "}");
                AppendLine(builder, depth, "}");
                break;
        }
    }

    private static void AppendFormatter(StringBuilder builder, string formatterName, int depth)
    {
        builder.Append('\n');
        AppendLine(builder, depth, $"private static string? {formatterName}(object? value)");
        AppendLine(builder, depth, "{");
        depth++;
        AppendLine(builder, depth, "if (value is null)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, "return null;");
        AppendLine(builder, depth, "}");
        builder.Append('\n');
        AppendLine(builder, depth, "if (value is string stringValue)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, "return stringValue;");
        AppendLine(builder, depth, "}");
        builder.Append('\n');
        AppendLine(builder, depth, "if (value is bool boolValue)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, "return boolValue ? \"true\" : \"false\";");
        AppendLine(builder, depth, "}");
        builder.Append('\n');
        AppendLine(builder, depth, "if (value is global::System.DateTime dateTimeValue)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, "return dateTimeValue.ToString(\"o\", global::System.Globalization.CultureInfo.InvariantCulture);");
        AppendLine(builder, depth, "}");
        builder.Append('\n');
        AppendLine(builder, depth, "if (value is global::System.DateTimeOffset dateTimeOffsetValue)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, "return dateTimeOffsetValue.ToString(\"o\", global::System.Globalization.CultureInfo.InvariantCulture);");
        AppendLine(builder, depth, "}");
        builder.Append('\n');
        AppendLine(builder, depth, "return global::System.Convert.ToString(value, global::System.Globalization.CultureInfo.InvariantCulture);");
        depth--;
        AppendLine(builder, depth, "}");
    }

    private static void AppendKeyFormatter(StringBuilder builder, string keyFormatterName, int depth)
    {
        builder.Append('\n');
        AppendLine(builder, depth, $"private static string {keyFormatterName}(object? key)");
        AppendLine(builder, depth, "{");
        AppendLine(builder, depth + 1, "return key is string stringKey ? stringKey : global::System.Convert.ToString(key, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;");
        AppendLine(builder, depth, "}");
    }

    private static string TypeKeyword(bool isRecord) => isRecord ? "partial record" : "partial class";

    private static string TypeParameters(EquatableArray<string> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        return $"<{string.Join(", ", typeParameters)}>";
    }

    private static string CamelCase(string name) => char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static string EscapeIdentifier(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;

    private static void AppendLine(StringBuilder builder, int depth, string text) =>
        builder.Append(' ', depth * 4).Append(text).Append('\n');
}
